### ISSUE TITLE
03-nzbget.sh fails, filesystem 

### ISSUE THREAD

**Issue by amizzo87** [chrisanthropic/PlexInTheCloud#22]
Have followed directions exactly, getting stuck at step 3:

`chown: cannot access '/home/[username]/AMZe': Permission denied
Job for rcloneMount.service failed because the control process exited with error code. See "systemctl status rcloneMount.service" and "journalctl -xe" for details.
sed: -e expression #1, char 24: unknown option to `s'`

Following instructions in error message, "systemctl status rcloneMount.service" gives this:

`Jan 14 17:17:07 plex-vultr systemd[1]: Starting Mount Amazon Cloud Drive...`
`Jan 14 17:17:07 plex-vultr bash[3729]: 2017/01/14 17:17:07 mount helper error: fusermount: failed to access mountpoint /home/[username]/AMZe: Permission denied`
`Jan 14 17:17:07 plex-vultr bash[3729]: 2017/01/14 17:17:07 Fatal error: failed to mount FUSE fs: fusermount: exit status 1`
`Jan 14 17:17:10 plex-vultr bash[3729]: Failed to open /home/[username]/AMZe/: Transport endpoint is not connected. Aborting!`
`Jan 14 17:17:10 plex-vultr systemd[1]: rcloneMount.service: Control process exited, code=exited status=1`
`Jan 14 17:17:10 plex-vultr systemd[1]: Failed to start Mount Amazon Cloud Drive.`
`Jan 14 17:17:10 plex-vultr systemd[1]: rcloneMount.service: Unit entered failed state.`
`Jan 14 17:17:10 plex-vultr systemd[1]: rcloneMount.service: Failed with result 'exit-code'.`

Any ideas?

**Comment by chrisanthropic** [comment]
That's odd. 

Here's what the script is doing:
  - it's stopping the rcloneMount.service
    - which unmounts your overlayFuseFS
    - then unmounts your Amazon Drive
  - then it's making sure your new user owns everything in home (since we've been issuing commands as the root user)

The error you're getting typically happens when the Amazon Drive mount isn't unmounted (it's mounted read-only so the chown command is unable to chown it which means the chown command errors out).

Also, did you run the `setup` and `rclone` scripts? All of the other scripts pretty much rely on the framework defined by those two.

If so, try running `sudo umount /path/to/your/amazon/drive/mount` and then running the script again.

**Comment by amizzo87** [comment]
That worked - thanks!

**Comment by chrisanthropic** [comment]
Problem should be fixed by #5ced121
