### ISSUE TITLE
Include deluge as an alternative.

### ISSUE THREAD

**Issue by zackbcom** [chrisanthropic/PlexInTheCloud#29]
Include deluge as an alternative to rtorrent.

http://deluge-torrent.org/

**Comment by chrisanthropic** [comment]
I'm fine adding most alternatives for most software, but as an FYI I'm aiming so that EVERY script can be run without interfering with each other, meaning that every script can be run and every piece of software will function as expected without overwriting files, messing with incomplete downloads, etc.

Not undoable at all, simply something to keep in mind.
