### ISSUE TITLE
Rclone mounted as read only

### ISSUE THREAD

**Issue by Antexa** [chrisanthropic/PlexInTheCloud#37]
Hi, 

Just wondering, why continue to using rclone in read only when the write support is implemented ? 

Antex'

**Comment by chrisanthropic** [comment]
Hi Antexa,

The main reason is that I haven't been able to get working configs for post-processing (renaming/moving) directly to the Rclone mount. I've got it set up but sometimes the PP works, sometimes it fails, sometimes it works on a video but fails on the .srt subtitle file, etc.

So, for now it's read-only because the PP workflow looks like this:

NZBGet downloads to ~/nzbget/completed/tv
nzbToMedia renames and moves to ~/LOCAL/tv
uploadTV.sh uploads the contents of ~/LOCAL/tv to Amazon Cloud Drive (using rclone move)
Sickrage reads/writes to ~/ALL
  - Since AMZe is mounted Read-Only Sickrage will read from it but write to ~/LOCAL

Plex reads from ~/AMZe (local Amazon Drive mount)
AMZe (local mount) refreshes every minute so the changes should be reflected quickly

I'm happy to get rid of the unionfsmount and read/write to rclone mount directly but I need reliable and consistent results. Once he introduces hash reading and caching hopefully it'll fix the issue.

That being said, if anyone has this setup working with only rclone mount I'd love to see it.

**Comment by OldMike** [comment]
Hi,

rClone supports r and w, not rw. And CP/SR need rw. I was told about a workaround using unionfs-fuse on the rclone forums: https://forum.rclone.org/t/rclone-native-encfs-support-hopfully-fixing-the-current-bug-where-you-cant-copy-paste-over-encfs-mount/497/13
I found a tutorial about it and I'll go for it by the weekend: (French one as I'm French sorry) https://upandclear.org/2017/01/19/rclone-utiliser-unionfs-fuse-pour-permettre-a-couchpotato-et-sickrage-de-lireecrire-sur-un-cloud-amazon/

**Comment by chrisanthropic** [comment]
Thanks @OldMike, I saw that thread on rclone forums. I used google translate to read the upandclear.org post and it should work fine, that's exactly the setup this project is using!
