### ISSUE TITLE
03-nzbget.sh feedback and or questions

### ISSUE THREAD

**Issue by Onyx369** [chrisanthropic/PlexInTheCloud#43]
Hey there,
I got home from work and tested out the nzbget.sh
Everything installed fine, which is great and I assume that it is running.
The issue is that it will not accept the nzbget default password nor did it make an account with the vars info.
So it pretty much just keeps deflecting me at the login prompt.

Any idea where I can find the config file that has the login / password info .... then I will just edit that file to contain the defaults login info so I can login.

Last question, does your script strip out the default account ? If so, can you consider a check to ensure that there is at least one account in the config file before it removes the default access?
If it does not remove default access then ignore my feedback and I must have broken something by accident.

Thanks

**Comment by chrisanthropic** [comment]
Hi,

the config file is at: /opt/nzbget/nzbget.conf

It (and all of the apps installed with these scripts) uses the username/password defined in the vars file, is that not working for you? For now that's how it's going to stay simply because this whole thing is somewhat complex and in order for it to work I expect a few things to be in order. This includes everything in the "setup" section as well as things defined in the vars file.

I hope I don't come across as mean about it, that's not my intent. I'm happy to make adjustments and fixes but I've working with limited free time and have to set some level of expectations. For now the expectation is that if you follow the guide then it should work. If that's incorrect then please let me know.

I'm always open to suggestions but that doesn't mean I'll always act on them.

**Comment by Onyx369** [comment]
Great stuff.

Thanks for the insight. Okay... here's what happened. For your bug testing interests.

I reviewed the /opt/nzbget/nzbget.conf

It added all of my settings from the VARS file (which is good).

It added my user name from VARS, no problems.... now this is where is went off the rails.
 
ControlPassword=lkj*ControlPassword=lkj*ControlPassword=lkj*ControlPassword=tegbzn6789^5

Then it added my VARS information seemly randomly a few times... to the same ControlPassword line

I logged into my remote site.... NANO'd the config file... and commented out the Control Password line. And then put in the single password from the VARS file... then restarted the service and was able to login just fine.

Thanks for pointing me in the direction of the config file and hope this bug testing assists you.

Onyx

**Comment by chrisanthropic** [comment]
Thanks for the info, I'll try to replicate soon. Sorry, but fixes are somewhat on hold for now while I work through the wiki (but I'm almost done!)

**Comment by chrisanthropic** [comment]
@Onyx369 - I tried on 2 previous installs and I just launched a brand new Ubuntu 16.04 instance on Linode, ran through the setup steps and ran the scripts up to this one and I can't replicate your issue.

Closing. I'll reopen if others can confirm the issue.
